# Day-15

In [2]:
import numpy as np

# 1. Create a 3x3x3 array with random values 

In [2]:
a = np.random.random((3,3,3))
print(a)

[[[0.53455312 0.26080025 0.91964446]
  [0.12516827 0.4896897  0.59115962]
  [0.07543078 0.41352121 0.69954411]]

 [[0.64390392 0.07631744 0.88215231]
  [0.19825242 0.73496278 0.68542261]
  [0.57680064 0.60260663 0.9152145 ]]

 [[0.11012824 0.68076767 0.03216835]
  [0.51182163 0.36471119 0.4699978 ]
  [0.72750719 0.4173785  0.61246886]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [22]:
a = np.zeros((5,5)int)
for i in range(4):
    a[i+1][i]=i+1

#Python one liner
a = np.diag(np.arange(1,5), k = -1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [28]:
a = np.zeros((8,8),int)
for i in range(8):
    for j in range(8):
        if (i&1 and j%2 == 0) or (i%2==0 and j&1):
            a[i,j] = 1

#Pythonic code
a = np.zeros((8,8),int)
a[1::2, ::2]= 1
a[::2, 1::2] = 1
print(a)
            

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [30]:
a = np.random.random((5,5))
maxx,minn = np.max(a),np.min(a)
a = (a - minn)/(maxx - minn)
print(a)

[[0.46915114 0.00883099 0.58702158 0.22697978 0.18435674]
 [0.0339071  0.66607016 0.98699827 0.01027623 1.        ]
 [0.59798007 0.56029575 0.30461223 0.37489583 0.15962004]
 [0.41195422 0.76483189 0.30576803 0.13214345 0.65235066]
 [0.10217597 0.         0.33120403 0.73507963 0.53385601]]


# 5.  How to find common values between two arrays?

In [3]:
a = np.arange(1,6)
b = np.arange(4,9)
print(np.intersect1d(a,b))

[4 5]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
import datetime
today = datetime.date.today()
yesterday = today - datetime.timedelta(days=1)
tomorrow = today + datetime.timedelta(days=1)
print("Today: ",today)
print("Yesterday: ",yesterday)
print("Tommorrow: ",tomorrow)

Today:  2020-07-26
Yesterday:  2020-07-25
Tommorrow:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [7]:
a = np.random.random((10,))
b = np.random.random((10,))
print(np.array_equal(a,b))

False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [14]:
a = np.random.random((10,))
print(a)
a[a.argmax()] = 0
print(a)

[0.40357667 0.51405699 0.26697542 0.54658876 0.46775301 0.75206644
 0.60681291 0.00323403 0.32522769 0.68443836]
[0.40357667 0.51405699 0.26697542 0.54658876 0.46775301 0.
 0.60681291 0.00323403 0.32522769 0.68443836]


# 9. How to print all the values of an array?

In [16]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


# 10.Subtract the mean of each row of a matrix

In [20]:
a = np.random.random((3,3))
print(a)
for row in a:
     row -= row.mean();
print(a)

[[0.31969441 0.09396699 0.53212727]
 [0.48504931 0.68742901 0.06039916]
 [0.82756273 0.91689449 0.2191803 ]]
[[ 0.00443152 -0.2212959   0.21686438]
 [ 0.07409015  0.27646985 -0.35056   ]
 [ 0.17301689  0.26234865 -0.43536554]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [29]:
a = np.ones((5,))
b = np.arange(5)
#Study about ufuncs
np.add.at(a,b,1)
print(a)

[2. 2. 2. 2. 2.]


# 12.How to get the diagonal of a dot product?

In [44]:
a = np.random.random((3,3))
b = np.random.random((3,3))
print(np.diag(np.dot(a,b)))

[0.65718535 0.20730935 0.40036857]


# 13.How to find the most frequent value in an array?

In [33]:
a = np.random.randint(0,10,50)
print(a)
print(np.bincount(a).argmax())

[7 5 7 0 3 2 2 6 7 7 1 0 2 7 8 7 7 1 6 5 5 2 4 3 6 0 8 6 0 2 5 1 0 7 1 5 9
 2 7 9 0 3 8 8 7 6 9 8 3 5]
7


# 14.How to get the n largest values of an array

In [43]:
a = np.random.randint(1,100,30)
print(a)
n = 5
#.argpartition returns index
print(a[np.argpartition(-a,n)[:n]])

[52 14 13 35 82 70 63  4 76 98 57 95 85 17 28 11 28 32 60 42 78 66 47 69
 61 93 33 93  6  2]
[98 95 93 93 85 82 69 78 76 70 66 52 33 63 61 35 47 32 60 42 57 28 28 11
 14 17  4 13  6  2]
[98 95 93 93 85]


# 15.How to create a record array from a regular array?

In [35]:
a = np.array([("Bonjour", 7.1, 2),
              ("Adios", 4.2, 3)])
record = np.core.records.fromarrays(a.T,
                               names='c1, c2, c3',
                               formats = 'S8, f8, i8')
print(record)

[(b'Bonjour', 7.1, 2) (b'Adios', 4.2, 3)]
